name: "Validate Gradle Wrapper"

on: [ pull_request ]

jobs:
  validation:
    name: "Validation"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.5
      - name: Change directory
        run: cd android
      - uses: gradle/wrapper-validation-action@v1
